### PR TITLE
New awooo graphics + color masking improvement

### PR DESCRIPTION
**Pull request by gabixdev**

### CODE REVIEW

**Comment by gabixdev** [comment]
yep

**Comment by DasWolke** [comment]
Do we need it though ? Does it add value ? 👀

**Comment by gabixdev** [comment]
someone may want it

**Comment by TheAkio** [comment]
We are currently rewriting Korra and we'll use node-canvas instead of Jimp. In addition we've already created the awooo generator. If you find something worth fixing in there you can do that once it's up.

**Pull request closed without merging**
